### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by phonikg**
I'm sure I posted this somewhere, but cannot find it.  I was successful in running the original armhf binary on BBB in addition to Wandboard and Odroid.

### CODE REVIEW

**Comment by bobsummerwill** [comment]
Thanks, John!    If you do find a Tweet, please let's add that link too :-)

**Comment by bobsummerwill** [comment]
Did you ever get the cross-build armhf running on your Raspberry Pi Model B+?
I think that's the last "status" which we don't have info from for your set of hardware.
C.H.I.P. is known broken / TODO.
Everything else works.  Right?
And the rest is down to me, because I have the hardware already (or will have when my parcels arrive!)

**Comment by phonikg** [comment]
If I do not find one I will create and then add.

**Comment by phonikg** [comment]
Raspberry Pi Model B+ - Will test soon(tomorrow)
FYI - Odroid XU3 & XU4 are 100% software compatible according to the manufacturer, therefore if you end up using the same image listed for XU3, they may not need a separate table entry... If you choose a different image/OS however...

**Comment by bobsummerwill** [comment]
Right ... I was being a little cagey there based on the Tizen story.
Their OS images _only_ work for the XU3.   Different kernel being built to support the slightly different hardware on the XU4.    Userland is apparently identical, though.
I've update the table to reflect that different OS.

*are* you using Ubuntu 15.04 MATE for your XU3?

**Pull request merged**
